package com.yichen.casetest.model;

import lombok.Data;
import lombok.ToString;

import java.math.BigDecimal;

@ToString
public class DataTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_test.id
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_test.money
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_test.name
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_test.id
     *
     * @return the value of data_test.id
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_test.id
     *
     * @param id the value for data_test.id
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_test.money
     *
     * @return the value of data_test.money
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_test.money
     *
     * @param money the value for data_test.money
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_test.name
     *
     * @return the value of data_test.name
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_test.name
     *
     * @param name the value for data_test.name
     *
     * @mbggenerated Mon Feb 07 16:03:46 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}